name: Manual Board Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # Используем официальный контейнер разработчиков ArduPilot
    container: ardupilot/ardupilot-dev-base:latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Build Rover Firmware
        run: |
          # Контейнер требует безопасного пути для Git
          git config --global --add safe.directory /__w/ardupilot/ardupilot
          # Конфигурируем и собираем
          ./waf configure --board SpeedyBeeF405WING
          ./waf rover

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SpeedyBeeF405WING-Rover
          path: build/SpeedyBeeF405WING/bin/ardupilot.apj
